export const RACES = [
  'human',
  'elf',
  'dwarf',
  'halfling',
  'orc',
  'tiefling',
  'dragonborn',
  'gnome',
] as const

export type Race = (typeof RACES)[number]

export const RACE_LABELS: Record<Race, string> = {
  human: 'Human',
  elf: 'Elf',
  dwarf: 'Dwarf',
  halfling: 'Halfling',
  orc: 'Orc',
  tiefling: 'Tiefling',
  dragonborn: 'Dragonborn',
  gnome: 'Gnome',
}

const NAME_PARTS: Record<Race, { first: string[]; last: string[] }> = {
  human: {
    first: [
      'Aldric',
      'Mira',
      'Tomas',
      'Elsbeth',
      'Garrick',
      'Lena',
      'Roderick',
      'Anya',
      'Cedric',
      'Isolde',
    ],
    last: [
      'Blackwood',
      'Thatcher',
      'Crowmere',
      'Fairwind',
      'Stonefield',
      'Ashby',
      'Hartley',
      'Welborn',
    ],
  },
  elf: {
    first: [
      'Aelar',
      'Thia',
      'Erevan',
      'Naivara',
      'Laucian',
      'Keyleth',
      'Soveliss',
      'Quelenna',
      'Adran',
      'Mialee',
    ],
    last: [
      'Moonwhisper',
      'Silverleaf',
      'Dawnstrider',
      'Nightbreeze',
      'Starflower',
      'Amakiir',
      'Galanodel',
      'Windshade',
    ],
  },
  dwarf: {
    first: [
      'Adrik',
      'Vistra',
      'Borin',
      'Helja',
      'Thoradin',
      'Amber',
      'Rurik',
      'Gunnloda',
      'Dain',
      'Eldeth',
    ],
    last: [
      'Ironfist',
      'Stonebeard',
      'Battlehammer',
      'Frostbeard',
      'Goldvein',
      'Fireforge',
      'Holderhek',
      'Deepdelver',
    ],
  },
  halfling: {
    first: [
      'Milo',
      'Rosie',
      'Alton',
      'Verna',
      'Cade',
      'Lidda',
      'Merric',
      'Andry',
      'Finnan',
      'Jillian',
    ],
    last: [
      'Goodbarrel',
      'Underbough',
      'Tealeaf',
      'Thorngage',
      'Greenbottle',
      'Highhill',
      'Brushgather',
      'Leagallow',
    ],
  },
  orc: {
    first: [
      'Krusk',
      'Shautha',
      'Thokk',
      'Vola',
      'Dench',
      'Emen',
      'Holg',
      'Neega',
      'Gell',
      'Ovak',
    ],
    last: [
      'Boneshatter',
      'Skullcleaver',
      'Ironjaw',
      'Bloodfang',
      'Ashwalker',
      'Stonecrusher',
      'Grimtusk',
      'Warbringer',
    ],
  },
  tiefling: {
    first: [
      'Akmenos',
      'Damaia',
      'Mordai',
      'Nemeia',
      'Therai',
      'Leucis',
      'Orianna',
      'Skamos',
      'Rieta',
      'Barakas',
    ],
    last: [
      'Embervein',
      'Ashmantle',
      'Duskwhisper',
      'Nightflame',
      'Shadowhorn',
      'Brimsoul',
      'Darkember',
      'Hellbrand',
    ],
  },
  dragonborn: {
    first: [
      'Arjhan',
      'Sora',
      'Balasar',
      'Akra',
      'Donaar',
      'Farideh',
      'Ghesh',
      'Kava',
      'Medrash',
      'Nala',
    ],
    last: [
      'Daardendrian',
      'Delmirev',
      'Kerrhylon',
      'Myastan',
      'Norixius',
      'Turnuroth',
      'Yarjerit',
      'Kimbatuul',
    ],
  },
  gnome: {
    first: [
      'Boddynock',
      'Ellywick',
      'Zook',
      'Bimpnottin',
      'Dimble',
      'Duvamil',
      'Fonkin',
      'Lorilla',
      'Namfoodle',
      'Roywyn',
    ],
    last: [
      'Beren',
      'Daergel',
      'Folkor',
      'Nackle',
      'Murnig',
      'Ningel',
      'Scheppen',
      'Timbers',
    ],
  },
}

function pick<T>(items: readonly T[]): T {
  return items[Math.floor(Math.random() * items.length)]
}

export function generateName(race: Race): string {
  const parts = NAME_PARTS[race]
  return `${pick(parts.first)} ${pick(parts.last)}`
}
